<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>KatzuoOgust.Promises.InMemory</AssemblyName>
    <RootNamespace>KatzuoOgust.Promises.InMemory</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Promises\Promises.csproj" />
  </ItemGroup>
</Project>
